//! 听歌模式官方场景图标（构建期内置，运行时零请求）。

pub const SCENE_ICONS: &[(&str, &[u8])] = &[
    (
        "scene_mode_bath",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_bath.png")),
    ),
    (
        "scene_mode_beach",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_beach.png")),
    ),
    (
        "scene_mode_bedtime",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_bedtime.png"
        )),
    ),
    (
        "scene_mode_breakup",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_breakup.png"
        )),
    ),
    (
        "scene_mode_calm",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_calm.png")),
    ),
    (
        "scene_mode_cantonese",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_cantonese.png"
        )),
    ),
    (
        "scene_mode_car_mode",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_car_mode.png"
        )),
    ),
    (
        "scene_mode_child",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_child.png")),
    ),
    (
        "scene_mode_chill",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_chill.png")),
    ),
    (
        "scene_mode_chinese_style",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_chinese_style.png"
        )),
    ),
    (
        "scene_mode_classic",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_classic.png"
        )),
    ),
    (
        "scene_mode_clean_up",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_clean_up.png"
        )),
    ),
    (
        "scene_mode_commute",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_commute.png"
        )),
    ),
    (
        "scene_mode_country",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_country.png"
        )),
    ),
    (
        "scene_mode_dj",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_dj.png")),
    ),
    (
        "scene_mode_douyin_roam",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_douyin_roam.png"
        )),
    ),
    (
        "scene_mode_drunk",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_drunk.png")),
    ),
    (
        "scene_mode_electronic",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_electronic.png"
        )),
    ),
    (
        "scene_mode_emo",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_emo.png")),
    ),
    (
        "scene_mode_english",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_english.png"
        )),
    ),
    (
        "scene_mode_fish",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_fish.png")),
    ),
    (
        "scene_mode_focus",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_focus.png")),
    ),
    (
        "scene_mode_folk",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_folk.png")),
    ),
    (
        "scene_mode_game",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_game.png")),
    ),
    (
        "scene_mode_get_up",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_get_up.png"
        )),
    ),
    (
        "scene_mode_happy",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_happy.png")),
    ),
    (
        "scene_mode_heal",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_heal.png")),
    ),
    (
        "scene_mode_jpop",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_jpop.png")),
    ),
    (
        "scene_mode_kpop",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_kpop.png")),
    ),
    (
        "scene_mode_ktv",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_ktv.png")),
    ),
    (
        "scene_mode_library",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_library.png"
        )),
    ),
    (
        "scene_mode_love_song",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_love_song.png"
        )),
    ),
    (
        "scene_mode_lucky",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_lucky.png")),
    ),
    (
        "scene_mode_lying_flat",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_lying_flat.png"
        )),
    ),
    (
        "scene_mode_night_time",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_night_time.png"
        )),
    ),
    (
        "scene_mode_non_vocal",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_non_vocal.png"
        )),
    ),
    (
        "scene_mode_nostalgic",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_nostalgic.png"
        )),
    ),
    (
        "scene_mode_rain",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_rain.png")),
    ),
    (
        "scene_mode_rap",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_rap.png")),
    ),
    (
        "scene_mode_rnb",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_rnb.png")),
    ),
    (
        "scene_mode_rock",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_rock.png")),
    ),
    (
        "scene_mode_slow_motion",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_slow_motion.png"
        )),
    ),
    (
        "scene_mode_sport",
        include_bytes!(concat!("../../../assets/icons/scenes/scene_mode_sport.png")),
    ),
    (
        "scene_mode_sweet_girl",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_sweet_girl.png"
        )),
    ),
    (
        "scene_mode_travel",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_travel.png"
        )),
    ),
];

pub const DARK_SCENE_ICONS: &[(&str, &[u8])] = &[
    (
        "scene_mode_bath-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_bath-dark.png"
        )),
    ),
    (
        "scene_mode_beach-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_beach-dark.png"
        )),
    ),
    (
        "scene_mode_bedtime-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_bedtime-dark.png"
        )),
    ),
    (
        "scene_mode_breakup-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_breakup-dark.png"
        )),
    ),
    (
        "scene_mode_calm-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_calm-dark.png"
        )),
    ),
    (
        "scene_mode_cantonese-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_cantonese-dark.png"
        )),
    ),
    (
        "scene_mode_car_mode-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_car_mode-dark.png"
        )),
    ),
    (
        "scene_mode_child-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_child-dark.png"
        )),
    ),
    (
        "scene_mode_chill-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_chill-dark.png"
        )),
    ),
    (
        "scene_mode_chinese_style-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_chinese_style-dark.png"
        )),
    ),
    (
        "scene_mode_classic-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_classic-dark.png"
        )),
    ),
    (
        "scene_mode_clean_up-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_clean_up-dark.png"
        )),
    ),
    (
        "scene_mode_commute-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_commute-dark.png"
        )),
    ),
    (
        "scene_mode_country-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_country-dark.png"
        )),
    ),
    (
        "scene_mode_dj-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_dj-dark.png"
        )),
    ),
    (
        "scene_mode_douyin_roam-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_douyin_roam-dark.png"
        )),
    ),
    (
        "scene_mode_drunk-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_drunk-dark.png"
        )),
    ),
    (
        "scene_mode_electronic-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_electronic-dark.png"
        )),
    ),
    (
        "scene_mode_emo-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_emo-dark.png"
        )),
    ),
    (
        "scene_mode_english-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_english-dark.png"
        )),
    ),
    (
        "scene_mode_fish-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_fish-dark.png"
        )),
    ),
    (
        "scene_mode_focus-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_focus-dark.png"
        )),
    ),
    (
        "scene_mode_folk-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_folk-dark.png"
        )),
    ),
    (
        "scene_mode_game-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_game-dark.png"
        )),
    ),
    (
        "scene_mode_get_up-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_get_up-dark.png"
        )),
    ),
    (
        "scene_mode_happy-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_happy-dark.png"
        )),
    ),
    (
        "scene_mode_heal-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_heal-dark.png"
        )),
    ),
    (
        "scene_mode_jpop-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_jpop-dark.png"
        )),
    ),
    (
        "scene_mode_kpop-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_kpop-dark.png"
        )),
    ),
    (
        "scene_mode_ktv-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_ktv-dark.png"
        )),
    ),
    (
        "scene_mode_library-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_library-dark.png"
        )),
    ),
    (
        "scene_mode_love_song-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_love_song-dark.png"
        )),
    ),
    (
        "scene_mode_lucky-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_lucky-dark.png"
        )),
    ),
    (
        "scene_mode_lying_flat-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_lying_flat-dark.png"
        )),
    ),
    (
        "scene_mode_night_time-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_night_time-dark.png"
        )),
    ),
    (
        "scene_mode_non_vocal-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_non_vocal-dark.png"
        )),
    ),
    (
        "scene_mode_nostalgic-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_nostalgic-dark.png"
        )),
    ),
    (
        "scene_mode_rain-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_rain-dark.png"
        )),
    ),
    (
        "scene_mode_rap-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_rap-dark.png"
        )),
    ),
    (
        "scene_mode_rnb-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_rnb-dark.png"
        )),
    ),
    (
        "scene_mode_rock-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_rock-dark.png"
        )),
    ),
    (
        "scene_mode_slow_motion-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_slow_motion-dark.png"
        )),
    ),
    (
        "scene_mode_sport-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_sport-dark.png"
        )),
    ),
    (
        "scene_mode_sweet_girl-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_sweet_girl-dark.png"
        )),
    ),
    (
        "scene_mode_travel-dark",
        include_bytes!(concat!(
            "../../../assets/icons/scenes/scene_mode_travel-dark.png"
        )),
    ),
];

pub fn dark_icon_bytes(name: &str) -> Option<&'static [u8]> {
    DARK_SCENE_ICONS
        .iter()
        .find(|(known, _)| *known == name)
        .map(|(_, bytes)| *bytes)
}

pub fn icon_bytes(name: &str) -> Option<&'static [u8]> {
    SCENE_ICONS
        .iter()
        .find(|(known, _)| *known == name)
        .map(|(_, bytes)| *bytes)
}
